# Generated by Django 4.1.3 on 2022-11-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
